### ISSUE TITLE
Empty turn

### ISSUE THREAD

**Issue by sanderland** [Zhou-Zoey/RMB-Reward-Model-Benchmark#1]
There is an empty turn here, is this on purpose?

https://github.com/Zhou-Zoey/RMB-Reward-Model-Benchmark/blob/main/RMB_dataset/Pairwise_set/Helpfulness/Translation/GeneralExcerpt%20Language%20Translation.json#L677

**Comment by Zhou-Zoey** [comment]
Thank you for pointing that out! The empty turn you mentioned is not intentional. It seems that there were some omissions during the data filtering process. We are aware of this issue and will release an updated version with these corrections in the future. We appreciate your understanding and patience!
